[workspace]
members = ["crates/*"]
default-members = [
    "crates/lib",
    "crates/backup",
    "crates/cleaner"
]

[profile.release]
opt-level= 2
lto = true
strip = true
panic = "abort"

# build with `cargo build --profile profiling`
# to analyze performance with tooling like linux perf
[profile.profiling]
inherits = "release"
strip = false
debug = true

# build with `cargo build --profile ci`
# to analyze performance with tooling like linux perf
[profile.ci]
inherits = "dev"
strip = false
debug = false
