[package]
name = "rebooter"
version = "0.1.0"
edition = "2021"

[lib]
name = "rebooter"
path = "src/lib.rs"

[[bin]]
name = "rebooter"
path = "src/main.rs"

[dependencies]
lib = { path = "../lib" }
clap = { version = "4.2.*", features = ["derive", "std"], default-features = false }
tokio = { version = "1.28.*", default-features = false, features = ["rt-multi-thread", "macros"] }
chrono = { version = "0.4.*", default-features = false }
uptime_lib = "0.2.2"

# Logging & Errors
tracing = "0.1.*"
thiserror = "1.0.*"
anyhow = "1.0.*"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.48", features = [ "Data_Xml_Dom", "Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging" ]}
registry = "1.2.3"

[dev-dependencies]
fake = { version = "2.6", features=["derive", "chrono", "maybe-non-empty-collections"]}
rand = "0.8"
