[package]
name = "rebooter"
version = "0.1.0"
edition = "2021"

[lib]
name = "rebooter"
path = "src/lib.rs"

[[bin]]
name = "rebooter"
path = "src/main.rs"

[dependencies]
lib = { path = "../lib" }

# Runtimes
tokio = { workspace = true }

# Cli & UI
clap = { workspace = true }

# Data & Serialization
chrono = { workspace = true, default-features = false }

# Logging & Errors
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

uptime_lib = "0.2.2"
sysexits = "0.7.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.51.1", features = ["Data_Xml_Dom", "Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }
registry = "1.2.3"

[dev-dependencies]
fake = { version = "2.6", features = ["derive", "chrono", "maybe-non-empty-collections"] }
rand = "0.8"
