[package]
name = "cleaner"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "system", "utilities", "cli"]
keywords = ["cleaner", "clean", "cleaning", "cleaning-tool", "cleaning-utility"]
description = "A cleaning tool written in Rust"

[dependencies]
lib = { path = "../lib" }
macros = { path = "../macros" }

cfg-if = "1.0"
clap = { version = "4.2.7", features = ["derive"] }
tokio = { version = "1.28.1", features = ["fs", "macros", "rt-multi-thread"] }
chrono = { version = "0.4.24" }
glob = "0.3.1"
inquire = "0.6.2"
indicatif = { version = "0.17.4", features = ["rayon"] }
rayon = "1.7"
michie = "3.0.2"
async-trait = "0.1.71"
lazy_static = "1.4.0"
downcast-rs = "1.2.0"

# Logging & Errors
tracing = "0.1.*"
tracing-subscriber = { version = "0.3.*", features = ["fmt"] }
thiserror = "1.0.*"
anyhow = "1.0.*"

[target.'cfg(unix)'.dependencies]
permissions = "0.4.1"
nix = { version = "0.26.2" }

[target.'cfg(windows)'.dependencies]

