[package]
name = "cleaner"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "system", "utilities", "cli"]
keywords = ["cleaner", "clean", "cleaning", "cleaning-tool", "cleaning-utility"]
description = "A cleaning tool written in Rust"

[dependencies]
tokio = { version = "1.28.1", features = ["fs", "macros", "rt-multi-thread"] }
anyhow = { version = "1.0.71", default-features = false }
lib = { path = "../lib" }
log = { version = "0.4.17", default-features = false }
once_cell = "1.17.1"
chrono = "0.4.24"
tokio-stream = "0.1.14"
async-trait = "0.1.68"
glob = "0.3.1"

[target.'cfg(unix)'.dependencies]
permissions = "0.4.1"

[profile.release]
opt-level = "s" # Optimize for size
strip = "debuginfo"
lto = "thin"

# build with `cargo build --profile profiling`
# to analyze performance with tooling like linux perf
[profile.profiling]
inherits = "release"
strip = false
debug = true

# build with `cargo build --profile ci`
# to analyze performance with tooling like linux perf
[profile.ci]
inherits = "dev"
strip = false
debug = false
