[package]
name = "backup"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "system", "utilities", "cli"]
keywords = ["backup"]

[features]
default = ["sources-s3", "sources-bitwarden", "sources-1password"]
binary-downloader = ["bytes", "rand", "const_format"]

sources-s3 = ["opendal", "futures"]
sources-bitwarden = ["binary-downloader"]
sources-1password = ["binary-downloader", "zip"]

[dependencies]
lib = { path = "../lib" }
macros = { path = "../macros" }

# Runtimes
tokio = { workspace = true }

# Cli & UI
clap = { workspace = true }
indicatif = { workspace = true, features = ["rayon"] }
inquire = { workspace = true }

# Data / Serialization
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
zip = { version = "0.6.6", features = ["zstd", "bzip2", "deflate", "deflate-zlib"], optional = true } # TODO :: Downsize features

# Networking
reqwest = { workspace = true }

# Logging & Errors
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

filetime = "0.2"
glob = "0.3.1"
async-trait = "0.1.68"
tokio-stream = "0.1.14"
readable-regex = "0.1.0-alpha1"

futures = { version = "0.3.28", optional = true } # Needed by opendal
opendal = { version = "0.37.0", features = ["services-s3", "rustls"], optional = true }

#tokio-util = { version = "0.7.8", features = ["full"] }
futures-util = "0.3.28"
rayon = "1.7"

# For downloading cli binaries
bytes = { version = "1.4.*", optional = true }
rand = { version = "0.8.*", optional = true }
const_format = { version = "0.2.31", optional = true }

[dependencies.value-bag]
version = "1.4.0"

[dev-dependencies]
# Logging & Errors
env_logger = "*"
test-log = { version = "0.2.12", features = ["trace"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

# Generating random data for tests
fake = { version = "2.6", features=["derive", "chrono", "serde_json", "maybe-non-empty-collections"]}
rand = "0.8"

# Fs & IO
tempdir = "0.3.7"

