[package]
name = "backup"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "system", "utilities", "cli"]
keywords = ["backup"]

[dependencies]
lib = { path = "../lib" }
filetime = "0.2"
glob = "0.3.1"
indicatif = { version = "0.17.4" }
rayon = "1.7"
serde_json = "1.0.96"
async-trait = "0.1.68"
futures = "0.3.28" # Needed by opendal
tokio-util = { version = "0.7.8", features = ["full"] }
futures-util = "0.3.28"
const_format = "0.2.31"

# For downloading the required cli
zip = { version = "0.6.6", default-features = true }
bytes = "1.4.0"
rand = "0.8.5"

[dependencies.reqwest]
version = "0.11.18"
default-features = false
features = ["gzip", "rustls"]

[dependencies.chrono]
version = "0.4.24"
default-features = false
features = ["serde"]

[dependencies.tokio]
version = "1.28.1"
default-features = true
features = ["rt-multi-thread", "macros", "full"]

[dependencies.opendal]
version = "0.37.0"
default-features = false
features = ["services-s3", "rustls"]

[dependencies.serde]
version = "1.0.163"
default-features = false
features = ["std", "derive"]

[dependencies.clap]
version = "4.2.7"
default-features = false
features = ["derive", "std", "help", "usage", "suggestions", "color"]

[dependencies.inquire]
git = "https://github.com/anwarhahjjeffersongeorge/inquire-filepath/"
branch = "filepath-select"
default-features = false
features = ["path","crossterm"]

[dependencies.value-bag]
version = "1.4.0"
