[package]
name = "country-ip"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "utilities", "cli", "library", "lib"]
keywords = ["random", "ip", "ip-address", "ipv4", "testing", "geoip", "geo", "country"]
description = "A command line utility to generate random IP addresses from a given country."

[lib]
name = "country_ip"
path = "src/lib.rs"

[features]
default = []
gui = ["iced", "iced_aw"]

[dependencies]
lib = { path = "../lib" }
macros = { path = "../macros" }

# Runtimes
tokio = { workspace = true }

# Cli & UI
clap = { workspace = true }

# Networking
reqwest = { workspace = true, features = ["stream"] }

# Logging & Errors
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

rand = { version = "0.8.5", features = ["small_rng"] }
async-compression = { version = "0.4.1", default-features = false, features = ["tokio", "gzip"] }
tokio-util = { version = "0.7.8", features = ["compat"] }
futures = "0.3.28"
cidr = "0.2.2"
async-trait = "0.1.72"

# Countries
keshvar = { version = "0.3.0", features = ["search-iso-short-name"] }

# GUI
iced = { workspace = true, optional = true }
iced_aw = { workspace = true, optional = true }

# Testing
[dev-dependencies]
env_logger = "*"
test-log = { version = "0.2.12", features = ["trace"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }
