name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths: [
      'flake.nix',
      'Cargo.toml',
      'Cargo.lock',
      'crates/**/src/**',
      'crates/**/Cargo.toml',
      '.github/workflows/ci.yml',
    ]

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_crates: ${{ steps.extract-crates.outputs.changed_crates }}
      rebuild_all: ${{ steps.check-root-changes.outputs.rebuild_all }}
      binaries: ${{ steps.generate-matrix.outputs.available_binaries }}
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Extract Changed Crates
        id: extract-crates
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.event.ref }} | grep -oP 'crates/[^/]+/' | sort -u)
          crates=$(echo "$changes" | sed -E 's/crates\/([^\/]+)\//\1/g' | sort -u)
          echo "changed_crates=$crates" >> "$GITHUB_OUTPUT"
          echo "Changed Crates: $crates"

      # If any of the root files have changed we should rebuild all crates.
      - name: Check for Root Changes
        id: check-root-changes
        if: ${{ steps.extract-crates.outputs.changed_crates == '' }}
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.event.ref }} | grep -oP '^(Cargo.toml|Cargo.lock|flake.nix|.github/workflows/ci.yml)$' | sort -u)
          if [ -n "$changes" ]; then
            echo "rebuild_all=true" >> "$GITHUB_OUTPUT"
            echo "All Crates will be rebuilt due to changes in root build files."
          fi
      
      - name: Generate Matrix
        id: generate-matrix
        run: |
          systems=("x86_64-linux" "aarch64-linux" "x86_64-windows" "aarch64-windows" "x86_64-darwin" "aarch64-darwin")

          if [ "${{ steps.check-root-changes.outputs.rebuild_all }}" == true ]; then
            crates=$(find crates -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
          else
            crates=${{ steps.extract-crates.outputs.changed_crates }}
          fi

          echo "Crates: $crates"
          if [ -z "$crates" ]; then
            echo "No crates have changed."
            echo "matrix={}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          cargo_metadata=$(cargo metadata --no-deps --format-version 1)
          default_members=$(echo "$cargo_metadata" | jq -r '.workspace_default_members[] | split("#")[0]' | xargs -n1 basename)
          echo "available_binaries=$(echo "$cargo_metadata" | jq -r '.packages | map(select(.targets[].kind[] | contains("bin")) | .name) | join(",")')" >> "$GITHUB_OUTPUT"
          
          # We only want to build the crates defined as default members.
          crates=$(echo "$crates" | grep -Fxf <(echo "$default_members"))

          echo "Default Members: $default_members"
          echo "Crates to Build: $crates"

          matrix="{\"system\": ["
          for system in "${systems[@]}"; do
            matrix+="\"$system\","
          done
          matrix="${matrix::-1}],\"crate\": ["
          for crate in $crates; do
            matrix+="\"$crate\","
          done
          matrix="${matrix::-1}]}"

          echo "$matrix" | jq .

          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build-artifacts:
    needs: [ get-changes ]
    if: ${{ needs.get-changes.outputs.matrix != '{}' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-changes.outputs.matrix) }}
    runs-on: ${{ endsWith(matrix.system, 'darwin') && 'macos-latest' || 'ubuntu-latest' }}
    name: Build ${{ matrix.crate }} for ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Swap Space
        if: ${{ !endsWith(matrix.system, 'darwin') && !env.ACT }}
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix build .#${{ matrix.crate }}-${{ matrix.system }}-dev -L --accept-flake-config

      - uses: actions/upload-artifact@v4.4.3
        if: ${{ contains(needs.get-changes.outputs.binaries, matrix.crate) && !env.ACT }}
        with:
          name: ${{ matrix.crate }}-${{ matrix.system }}
          path: result/bin/
          if-no-files-found: error

  run-tests:
    needs: [ get-changes, build-artifacts ]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-changes.outputs.matrix) }}
    runs-on: ${{ endsWith(matrix.system, 'darwin') && 'macos-latest' || 'ubuntu-latest' }}
    name: Run Tests for ${{ matrix.crate }} on ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Should we run tests?
        id: should-run-tests
        run: |
          matrix_system="${{ matrix.system }}"
          
          # If the system ends with windows we should skip the tests.
          if [[ "$matrix_system" == *windows ]]; then
            echo "run_tests=false" >> "$GITHUB_OUTPUT"
          fi

          # We only want to run native tests on the runner that matches the host system.
          host_system=$(nix eval --raw nixpkgs#system)
          if [[ "$matrix_system" == "$host_system" ]]; then
            echo "run_tests=true" >> "$GITHUB_OUTPUT"
          fi

          echo "run_tests=false" >> "$GITHUB_OUTPUT"

      - name: Run Tests
        if: ${{ steps.should-run-tests.outputs.run_tests == 'true' }}
        run: nix develop --impure -c cargo nextest run --package ${{ matrix.crate }} --all-features

      - name: Run Doc Tests
        if: ${{ steps.should-run-tests.outputs.run_tests == 'true' }}
        run: nix develop --impure -c cargo test --doc --package ${{ matrix.crate }}
