name: Continuous Integration

on:
  push:
    branches: [master]
    paths: [
      '**/src/**',
      '.github/workflows/ci.yml',
      'flake.nix'
    ]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix flake check --impure -L

  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix build .#release

      - uses: actions/upload-artifact@v4.4.3
        if: ${{ !github.event.act }}
        with:
          name: tools
          path: result/bin/
          if-no-files-found: error
