name: Continuous Integration

on:
  push:
    branches: [master]
    paths: [ '*/src/**', '.github/workflows/ci.yml' ]

jobs:
  fmt-clippy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain and Cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Cargo clippy
        run: |
          cargo clippy --workspace -- -D warnings

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain and Cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
        with:
          toolchain: nightly
          target: ${{ matrix.target }}

      - name: Run tests
        run: |
          cargo test --workspace --profile ci

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain and Cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
        with:
          toolchain: nightly
          target: ${{ matrix.target }}

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run Tests
        shell: bash
        run: |
          source <(cargo llvm-cov show-env --export-prefix)
          cargo llvm-cov clean
          cargo build --workspace --profile ci
          cargo test --workspace --profile ci
          cargo llvm-cov report --profile ci --lcov --output-path lcov.info

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
