name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths: [
      'crates/**/src/**',
      'crates/**/Cargo.toml',
      'crates/**/Cargo.lock',
      '.github/workflows/ci.yml',
      'flake.nix'
    ]

jobs:
  build-artifacts:
    strategy:
      fail-fast: false
      matrix:
        crate:
          - amt-lib
          - amt-macros
          - backup
          - country-ip
          - memorable-pass
          - sys-cleaner
        system:
          - x86_64-linux
          - aarch64-linux
          - x86_64-windows
          - aarch64-windows
          - x86_64-darwin
          - aarch64-darwin

    runs-on: ${{ endsWith(matrix.system, 'darwin') && 'macos-latest' || 'ubuntu-latest' }}
    name: Build ${{ matrix.crate }} for ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Swap Space
        if: ${{ !endsWith(matrix.system, 'darwin') }}
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix build .#${{ matrix.crate }}-${{ matrix.system }}-dev -L --accept-flake-config

      - uses: actions/upload-artifact@v4.4.3
        if: ${{ !github.event.act }}
        with:
          name: ${{ matrix.crate }}-${{ matrix.system }}
          path: result/bin/
          if-no-files-found: error

  run-tests:
    needs: [ build-artifacts ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix flake check --impure --allow-import-from-derivation -L --keep-going
