name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or Tag to build'
        required: true
        default: 'master'
        type: string
      runner:
        description: 'Runner to use for the build'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  build-artifacts:
    runs-on: ${{ github.event.inputs.runner }}
    name: Debug Build ${{ github.event.inputs.ref }} on ${{ github.event.inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Swap Space
        if: ${{ !endsWith(github.event.inputs.runner, 'darwin') }}
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Setup tmate session for debugging
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          limit-access-to-actor: true
