name: Create Release

on:
  - workflow_call # Disable this for now.

#on:
#  workflow_dispatch:
#  push:
#    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: result/bin/*
          file_glob: true
          asset_name: tools-${{ github.ref }}
          tag: ${{ github.ref }}

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Generate the Changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest

  publish:
    name: Publish Release
    needs: [ prepare, changelog ]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ needs.changelog.outputs.release_body }}
