name: Create Release Draft

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  run:
    # TODO :: Add apple targets
    strategy:
      matrix:
        target:
        - x86_64-pc-windows-gnu
        - x86_64-unknown-linux-gnu
        extra: ['']
        include:
        - target: x86_64-pc-windows-gnu
          os: windows-latest
          suffix: '.exe'
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain and Cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
        with:
          toolchain: nightly
          target: ${{ matrix.target }}

      - name: Run
        run: |
          cargo build --workspace --release --target ${{ matrix.target }}

      - name: Publish Archive
        uses: softprops/action-gh-release@v0.1.13
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: true
          files: |
            target/${{ matrix.target }}/release/*.${{ matrix.suffix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
